#!/bin/bash

aapt package -M AndroidManifest.xml -I ../system/bundle.apk -S res -x 97 -F bundle.apk -f && \
unzip bundle.apk resources.arsc && \
mv resources.arsc bags.arsc && \
xxd -i bags.arsc > bags_arsc.h
