LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_ADDITIONAL_DEPENDENCIES := $(LOCAL_PATH)/Android.mk

ifeq ($(TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE),true)
   LOCAL_CFLAGS += -DREQUIRES_SYNCHRONOUS_SETSURFACE
endif

LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE := libhwui

include $(LOCAL_PATH)/Android.common.mk

include $(BUILD_SHARED_LIBRARY)

include $(call all-makefiles-under,$(LOCAL_PATH))
